### ISSUE TITLE
Should passport-google-oauth work for a Google+ account?

### ISSUE THREAD

**Issue by ginnyd** [jaredhanson/passport-google-oauth#10]
Does this library work fully with Google+?  When I configure this to work with Google+ I do not seem to be getting back the information I would expect for the user profile.  The reason I ask this is if I follow the examples from Google on implementing a Google+ Login Button (https://developers.google.com/+/quickstart/) I get my full profile sent back.  When I use passport-google-oauth I do get some profile information back, it is just a subset of what I expect.  I've been looking at the internals of both projects trying to figure out if they are doing the same thing under the covers but haven't been able to figure it out yet, so I figured I would post my question here. 

For the code I am using for passport-google-oauth I am using the oAuth2 example from the readme.  The only change I had to make to it other than adding my google credentials was to add a scope on the /auth/google get handler as follows:

	app.get('/auth/google', passport.authenticate('google', {scope: 'https://www.googleapis.com/auth/plus.login'}));

I did this because Google raised an error back to me stating I needed a scope.

Thanks in advance for any guidance.

Ginny

**Comment by jaredhanson** [comment]
This module has now been updated to use Google+.
