### ISSUE TITLE
id_token Google OAuth2

### ISSUE THREAD

**Issue by kayomarz** [jaredhanson/passport-google-oauth#108]
Using Google OAuth2, how do you get hold of the id_token apart from the access_token or refresh_token?

**Comment by kayomarz** [comment]
Solution: If 5 parameters are passed to the callback of the strategy, the 4th parameter has this info.
Found this solution here: https://github.com/jaredhanson/passport-google-oauth/issues/6#issuecomment-11054352

    passport.use(new passportGoogleOAuth2.OAuth2Strategy(
      {...}, // credentials
      function(accessToken, refreshToken, X, profile, done) {
        // X.id_token
      }));

**Comment by prabhakarupadhyay** [comment]
wow thx man u saved my life...cheers!!

**Comment by gharShaddi** [comment]
how to pass id_token in httprequest is it with headers or body or query or parms or what ?

**Comment by nayefmhmd85** [comment]
kayomarz  , You saved My day

**Comment by Jmiguel14** [comment]
Someone knows how to solve this in nestjs, because in nestjs I am using the validate method but I cannot acces the params param in the method :'c

This is my class: 
`js
@Injectable()
export class GoogleStrategy extends PassportStrategy(Strategy, 'google') {
  constructor(private readonly authService: AuthService) {
    super({
      clientID:
        '232269133872-071up030t7elncvk8t0loi7cue214ctl.apps.googleusercontent.com',
      clientSecret: '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',
      callbackURL: 'http://localhost:8080/auth/google/callback',
      scope: ['email', 'profile'],
    });
  }

  async validate(
    accessToken: string,
    refreshToken: string,
    profile: IProfile,
    done: VerifyCallback,
  ): Promise<void> {
    console.log({ accessToken, refreshToken, profile, done });
    const { name, emails, photos } = profile;
    const googleUser = {
      email: emails[0].value,
      firstName: name.givenName,
      lastName: name.familyName,
      picture: photos[0].value,
      accessToken,
    };
    const user = await this.authService.googleLogin(googleUser);
    console.log(user);

    done(null, { ...googleUser, _id: user._id });
  }
}
`
