### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by kodekrendel** [jaredhanson/passport-google-oauth#125]
Hi.

Am I suppose to already know how to use this package, even if I see it first time?
Or may be I must relay to other people chaotic tutorials?

Where is documentation?

**Comment by hmontes** [comment]
You can see documentation here: https://github.com/jaredhanson/passport-google-oauth2

Remember. This package combines passport-google-oauth1 and passport-google-oauth20

**Comment by kodekrendel** [comment]
Oh, thank you!
