### ISSUE TITLE
OAuth2Strategy requires a verify callback  how to fix it?

### ISSUE THREAD

**Issue by lagmanzaza** [jaredhanson/passport-google-oauth#126]
![888](https://cloud.githubusercontent.com/assets/5283709/26555415/21903658-44bf-11e7-83d8-52c5385da770.PNG)

**Comment by amp89** [comment]
I had this same problem and it drove me insane for like an hour...

You are calling it like 
passport.use(new GoogleStrategy({}), function(){} )
but it should be:
passport.use(new GoogleStrategy(  {}, function(){} ) ) //Note where I moved the parenthesis

GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

**Comment by lagmanzaza** [comment]
I fixed it by enabling Google+ API because It is important for authentication

**Comment by roganoalien** [comment]
@amp89 you basically saved me, was driving me crazy too!!!

**Comment by yogi4you** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

Oh thank you sir. You are a saver

**Comment by utkarshdubey** [comment]
Lol, I was following a tutorial. I think there should be some things people should keep in mind before posting tutorials.

**Comment by malithkuruwita** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

you are a savior

**Comment by shweta1907** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().



> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

you saved me from wasting 1hr,thank you

**Comment by nhoon95** [comment]
You are my savior

**Comment by LastSkyFall** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

Lord and saviour

**Comment by sajjadmrx** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like
> passport.use(new GoogleStrategy({}), function(){} )
> but it should be:
> passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

** You are my savior :)))) **

**Comment by shivavishnoi** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like passport.use(new GoogleStrategy({}), function(){} ) but it should be: passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

Thank You Very Much!!

**Comment by StevenMODIMO** [comment]
Solution by amp89 worked

**Comment by ranaadeel15911** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like passport.use(new GoogleStrategy({}), function(){} ) but it should be: passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

Amazing sir

**Comment by Juhyeok0202** [comment]
> I had this same problem and it drove me insane for like an hour...
> 
> You are calling it like passport.use(new GoogleStrategy({}), function(){} ) but it should be: passport.use(new GoogleStrategy( {}, function(){} ) ) //Note where I moved the parenthesis
> 
> GoogleStrategy takes 2 arguments, the first is the object with the id/secret/url, and the 2nd is the function, and new GoogleStrategy is the only thing you pass into passportjs.use().

thk!
