### ISSUE TITLE
Missing required parameter: scope" in app serverless

### ISSUE THREAD

**Issue by MAPESO** [jaredhanson/passport-google-oauth#135]
Hi, I'm creating an authentication service through a "serverless" architecture. I'm not using Express or Connect.

<img width="690" alt="screen shot 2018-12-03 at 00 19 23" src="https://user-images.githubusercontent.com/16585386/49356387-34b88980-f691-11e8-822b-2afb422d0821.png">

### Expected behavior

I'm passing the necessary arguments to the method, it should work.

### Actual behavior

users who understand how passport works will know that the `passport.authenticate()` method returns an  `return (req, res, next) => {}`. I'm initializing the authentication method before, but I can not make it work.

```js

const auth = passport.authenticate('google', {
  scope: ['https://www.googleapis.com/auth/plus.login']
});

const callback = passport.authenticate('google', {
  failureRedirect: '/auth.js',
  successRedirect: '/'
});

module.exports = (req, res) => {
  const { query } = parse(req.url, true);
  if (query.callback) {
    callback(req, res, () => {});
  } else {
    auth(req, res);
  }
};

```
It would be very helpful if someone can tell me how to make passport work :D

### Environment

* Operating System: macOS Mojave **(10.14.1)**
* Node version: 11.3.0
* passport version: 0.4.0
* passport-google-oauth version: 1.0.0

**Comment by artseven** [comment]
add scope on callback just like you did for auth

**Comment by gavin-c-tcg** [comment]
in my case, I forget to register `passport.initialize()` middleware
