### ISSUE TITLE
Upgrade to use v3 of userinfo endpoint?

### ISSUE THREAD

**Issue by x1a0** [jaredhanson/passport-google-oauth#22]
The new endpoint is:

    https://www.googleapis.com/oauth2/v3/userinfo

Current this module uses version 1:

    https://www.googleapis.com/oauth2/v1/userinfo

**Comment by ilanbiala** [comment]
Is it already deprecated? Does switching it break anything?

**Comment by jaredhanson** [comment]
The strategy has been updated to use the Google+ endpoint, which is recommended over any version of the user info endpoint.
