### ISSUE TITLE
Can't access "expires_in" parameter

### ISSUE THREAD

**Issue by maxbrodie** [jaredhanson/passport-google-oauth#23]
Unless I'm missing something, in addition to an access token, a refresh token, and a profile the verify function should also have expires_in as a parameter. 

From https://developers.google.com/accounts/docs/OAuth2UserAgent#handlingtheresponse

"Other parameters included in the response include expires_in and token_type. These parameters describe the lifetime of the token in seconds, and the kind of token that is being returned."

**Comment by rsahukrishworks** [comment]
i am able to get the refresh token but it is not a valid refresh token when i try to using it to fetch a new access token using  the token api of google its responding invalid refresh token refresh token is not valid. 

```javascript
passport.use(new GoogleStarategy({
    clientID: process.env.GOOGLE_AUTH_CLIENTID,
    clientSecret: process.env.GOOGLE_AUTH_CLIENT_SECRET,
    accessType: 'offline',
    callbackURL: uris.GOOGLE_CALLBACK_URL,
}, async (accessToken, refreshToken, params, profile, cb) => {
    console.log({refreshToken})
    return cb(null, result)
}));

authRoutes.route('/login/google').get(passport.authenticate('google', { 
    scope: ["profile", "email"],
    session:false,approvalPrompt: 
    'force',accessType: 'offline'}));
    
   authRoutes.route('/google/callback').get(passport.authenticate('google', {
    session:false,
    failureMessage: 'cannot login please try agin later',
    failureRedirect: uris.FAILURE_GOOGLE_LOGIN_URL,
    successRedirect: uris.SUCCESS_GOOGLE_LOGIN_URL
}), (req,res) => {
    // console.log("callback",req)
    // res.send().json(req)
});
```

**Comment by AbrehamT** [comment]
> There's a 5-argument form of the verify callback, like this:
> 
> ```
> function(accessToken, refreshToken, params, profile, done) {
>   console.log(params.expires_in);
>   // save tokens and expiry time
> }
> ```
> 
> `params` contains all the parameters in the OAuth 2.0 response, including the expiration time.
> 
> As to your SO question, Passport doesn't use the access token or refresh token in any way, except to fetch the user profile. If you want to use the refresh token to obtain a new access token, you'll need to do that in your backend processes.

Does this work with passport-google-oauth20 and/or passport-azure-ad-oauth20?
