### ISSUE TITLE
passReqToCallback is not working as expected ? 

### ISSUE THREAD

**Issue by alexis-gruet-deel** [jaredhanson/passport-google-oauth#44]
I would like to take advantage of the `passReqToCallback` attribute from the `GoogleStrategy()` object. 
Fyi : `passReqToCallback` allow to get the request object from `GoogleStrategy` callback. Prototype become like this : 

``` javascript
function( request, accessToken, refreshToken, profile, done )
```

However, and maybe this is b/c of the way google auth works, the session is regenerated between the verb /auth/google and /auth/google/callback which lead to lost the sessionID. 

please note on facebook strategy it works like a charm. 

As a example of the request.session coming from the GoogleStrategy callback : 

``` javascript
 sessionStore: 
   { sessions: { nkCqHOvI7SLbBzaeWPCCWU4AOFmMA_Yx: '{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{},"client_id":"BASNnJDGFyn-dtXHAAAB"}' },
....
 sessionID: 'MW76gNUj17bEURYKztmfofH1HH6dhI8S',
```

Any idea ?

**Comment by dancingshell** [comment]
@MI-LA01 i know this was a long time ago, but how did you fix this locally?

**Comment by MI-LA01** [comment]
Wow... it was a long time ago... Read the README.md via the fork i made, 

https://github.com/MI-LA01/passport-google-oauth

There is few notes regarding local, good luck.
