### ISSUE TITLE
How to add the "hd"-parameter to the request?

### ISSUE THREAD

**Issue by pakastin** [jaredhanson/passport-google-oauth#5]
Title says it all.. I would like to limit login to a certain domain only - how can I add the parameter to the request?

**Comment by adamjhickey** [comment]
For OAuth2, add the hostedDomain property on the same object where you add your scopes.

**Comment by bshandley** [comment]
> For OAuth2, add the hostedDomain property on the same object where you add your scopes.

It's also an array, so hostedDomain: ['domain.com']
