### ISSUE TITLE
Still well maintained?

### ISSUE THREAD

**Issue by binarykitchen** [jaredhanson/passport-google-oauth#50]
Or should I consider https://github.com/shobhitsinghal624/passport-google-authcode ?

**Comment by ilanbiala** [comment]
@sqrrrl does that support the state parameter?

**Comment by sqrrrl** [comment]
@ilanbiala No, but been meaning to add it along with pure server-side flows. Right now it is written to be used with the G+ sign-in button to initiate the auth requests.

**Comment by jaredhanson** [comment]
All outstanding and relevant pull requests on this package have been merged and a new, up-to-date version is on npm.
