### ISSUE TITLE
OAuth 2.0 Endpoints changing

### ISSUE THREAD

**Issue by ahildoer** [jaredhanson/passport-google-oauth#53]
Hi, 

Google has deprecated the end points used for OAuth 2.0. See https://developers.google.com/+/api/auth-migration#timetable

They suggest updating to new end points for OAuth 2.0 as well as changing some scope items for getting a profile. https://developers.google.com/+/api/auth-migration#oauth2login

My concern is that this library has had no commits for nearly a year. If I do a pull request to make these changes, can we can another deployment of this with those changes to NPM? 

Thanks!

**Comment by longlh** [comment]
I have create a pull request to support this issue, please check https://github.com/jaredhanson/passport-google-oauth/pull/63

**Comment by jaredhanson** [comment]
Published passport-google-oauth@0.2.0 to npm, which updates to Google's new API endpoints.
