### ISSUE TITLE
Import Google/Facebook contacts with online/offline status.

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [jaredhanson/passport-google-oauth#55]
Hello,Can i import Google/Facebook contacts with respective user's online/offline status using passport authentication.?If any idea please  share with some code code snippet or some useful links.

**Comment by jaredhanson** [comment]
I don't follow exactly, but this module is only concerned with authentication, during which you get an access token.  You can use that access token to make whatever API calls are allowed, but its up to you past that point.
