### ISSUE TITLE
Set login_hint when signing a user in based on email

### ISSUE THREAD

**Issue by ilanbiala** [jaredhanson/passport-google-oauth#61]
It would be nice to set the `login_hint` based on the email when signing a user in.

**Comment by ilanbiala** [comment]
Bump.

**Comment by ilanbiala** [comment]
@jaredhanson any idea how to do this dynamically based on each user authentication?

**Comment by jaredhanson** [comment]
Wrap passport calls to pick off dynamic options.

function authenticateWithHint(req, res, next) {
    var loginHint = myUser.whatever;
    passport.authenticate('google', { loginHint: loginHint })(req, res, next);
}
