### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by alexkahn** [jaredhanson/passport-google-oauth#67]
Attempted to find the code that produces the following: 

```
createCredentials() is deprecated, use tls.createSecureContext instead
```

in this repository and the corresponding passport-oauth2 module. Not sure what is causing this but I'm 99% it's got something to do with passport.

**Comment by jaredhanson** [comment]
I'm 99% that Passport or the OAuth 2-based strategies call `createCredentials()` anywhere.  Could you do some more investigation into this to confirm that this is actually an issue with this project?

**Comment by jaredhanson** [comment]
Confirmed.  This call is in the underlying `oauth` module, as described in [node-oauth/#196](https://github.com/ciaranj/node-oauth/issues/196).  The code itself is not needed, as seen in the [node-oauth/#240](https://github.com/ciaranj/node-oauth/pull/240) patch.  When that patch is merged and published, the warning will go away.

**Comment by alexkahn** [comment]
Thanks!

**Comment by andela-bojengwa** [comment]
thanks. :+1:
