### ISSUE TITLE
Update and extend examples

### ISSUE THREAD

**Issue by ilanbiala** [jaredhanson/passport-google-oauth#70]
Using Passport really requires developers to read the code and understand it, which is somewhat frustrating because it's built in many different interconnected pieces. It would be nice if the examples were up-to-date regarding dependencies and also showcased all of the features of Passport.

**Comment by jaredhanson** [comment]
There's outstanding pull requests which update examples, and many articles to be found on the web.  Closing this issue, since it is not a personal priority of mine to document it more extensively than I already have.  If you want to put together examples of your own that you feel are better, I'd be happy to include them.

**Comment by ilanbiala** [comment]
What's the point of writing a library if the only way to use its feature is to read and understand all of its code, which is worse than having to write your own...Documentation should be a priority...especially because you don't want to add a contributor to Passport to continue development and maintenance at a rate that satisfies the community.

**Comment by jaredhanson** [comment]
Please feel free to write documentation and code then.  I'll add you as a contributor if you step up and deliver solutions to address the issues you mention.

**Comment by ilanbiala** [comment]
@jaredhanson let's start to resolve this by getting all the PRs and issues out of the way, then we'll reevaluate where everything is at.

**Comment by jaredhanson** [comment]
Since I do this for free on my own time, I'll start by working and reevaluating against and my own priorities.  Thanks.
