### ISSUE TITLE
Google OAuth2Strategy login scopes

### ISSUE THREAD

**Issue by nsampietro** [jaredhanson/passport-google-oauth#79]
Hi, I only want to get the user's basic information an email, I tried all the below scopes:
'profile email'
'profile'
'email'

But  the google authorization page keeps  saying the application is requesting to  "Have offline access". I don't understand why. Does anyone else ran into this?.

Thanks

**Comment by harigopalakrishna** [comment]
I have same issue

**Comment by nsampietro** [comment]
More info: When the application is authorized for the first time, It prompts for the correct permissions (email, basic profile info). After that, I keep getting the "Have offline access" permission message when I try to log in with the same user. 
It should not prompt for any permission since the app was already authorized. If I go to the user account settings I see the "basic profile info" granted to the application.

**Comment by nsampietro** [comment]
ok, the problem was a prompt: 'consent' value accidentally included on the request.   
Please close this issue.

**Comment by jetsonjohn** [comment]
I got the same issue I have added the prompt none but still google showing with screen "Have offline access"

Below is my code in sails app

```javascript
module.exports.passport = {
  google: {
    name: 'Google',
    protocol: 'oauth2',
    strategy: require('passport-google-oauth').OAuth2Strategy,
    options: {
      clientID: 'xxxxxxxx',
      clientSecret: 'xxxxxxxxxxx',
      prompt:'none', 
      accessType: 'online',
      approvalPrompt: 'auto', 
      scope: ['email'],
    }
  },
}
```

Does anyone have any idea on this?
