### ISSUE TITLE
Passport strategy never called on callback, code parameter in URL??

### ISSUE THREAD

**Issue by tomismore** [jaredhanson/passport-google-oauth#89]
I have everything set up pretty much as is in the example, but when I log in with Google, it redirects to

http://localhost:9657/auth/google/callback?code=4%2FVHdcApFOjgPX4MRDCCpcd0hT3OCPkU2_Z8wbX2cQvJA&authuser=0&prompt=consent&session_state=8921f122d4aded87e026d21b65705b213255d18f..7bd5

and the passport strategy callback (where I would normally check my database for the googleID) is never called.

I feel like I'm missing something basic here but I just don't know what.

**Comment by tomismore** [comment]
Never mind. Routing error.

**Comment by emnh** [comment]
@tomismore I'm getting the same. What exactly was the routing error?

**Comment by tomismore** [comment]
Honestly I can't quite remember, but I think I'd literally just put in my URL to Google wrong or had a spelling mistake in my route handler. Sorry I can't be more helpful. My only advice is triple-check all of your routes
